Repository NangBT/LearnGit, pull requests merged in 2024-01, with the labels that each got.

#2 #1 - [Done] [Api] Complete Register api for Customer app
  Customer.txt
Labels: merge

#5 #4 - [Done] [Api] Customer Login
  Customer.txt
Labels: merge

#8 #7 - [Done] [Api] Customer complete profile
  Customer.txt
Labels: merge

#11 #1 - [Done] [Api] Send email to customer after register account
  Customer.txt
Labels: hotfixes

#15 #13 [Done] [Api] Customer get profile
  Customer.txt
Labels: feature

#16 #14 [Done] [Api] Activate customer account
  Customer.txt
Labels: hotfixes

#17 #1, #13 Hotfixes/14 customer activate account
  Customer.txt
Labels: merge

#22 #19 - [Done] [Api]: Customer create booking
  Customer.txt
Labels: feature

#23 #20 - [Done] [Api]: Customer update device
  Customer.txt
Labels: hotfixes

#24 Hotfixes/20 customer update device
  Customer.txt
Labels: merge
